version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.5
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

jobs:
  python-fmt:
    docker:
      - image: cytopia/black
    steps:
      - checkout
      - run: |
          python -m black --check --diff ./src/scripts
  adjust-orb:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          # default orb-dir
          at: ./dist/
      - run:
          name: adjust orb.yml
          command: yq -i '.examples.config_yml.usage.setup = true' ./dist/orb.yml
      - persist_to_workspace:
          paths:
            - orb.yml
          root: ./dist/

workflows:
  lint-pack:
    jobs:
      - python-fmt:
          filters: *filters
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - adjust-orb:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - orb-tools/publish:
          orb-name: dr666m1/yaml-bundler
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack]
          context: orb-publishing
          filters: *filters
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
