version: 2.1
orbs:
  iay: dr666m1/include-another-yaml@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  python-tests:
    executor: iay/default
    steps:
      - checkout
      - run:
          working_directory: src/scripts
          command: |
            pip install pyyaml jsonpath-ng
            python -m unittest test.py
  command-tests:
    executor: iay/default
    steps:
      - checkout
      # Testing just one YAML file is enough as all files are testted in python-tests.
      - iay/include:
          filepath: testcase/input/simple.yml

workflows:
  test-deploy:
    jobs:
      - python-tests:
          filters: *filters
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: dr666m1/include-another-yaml
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
