description: >
  This command handles !include tag inside YAML file.
  The file will be overwritten.

  NOTE: Consider using `continue` job if the file is used
  as a configuration file which is passed to the continue API.

parameters:
  filepath:
    type: string
    description: "YAML file which includes !include tag"

steps:
  - s2f/str2file:
      str: << include(scripts/main.py) >>
  - run:
      name: 'handle !include tag'
      environment:
        PARAM_FILEPATH: << parameters.filepath >>
      command: |
        pip install pyyaml jsonpath-ng
        python str2file-out
