description: >
  In the simplest case, config.yml looks like this.

  NOTE: Enable dynamic config on project settings page.
  NOTE: Don't forget `setup: true`. I don't know why, but it does not apper in this example :-(

usage:
  version: 2.1
  setup: true
  orbs:
    yaml-bundler: dr666m1/yaml-bundler@0
  jobs:
    setup:
      executor: yaml-bundler/default
      steps:
        - checkout
        - yaml-bundler/bundle:
            filepath: main.yml
        - continuation/continue:
            configuration_path: main.yml
  workflows:
    setup:
      jobs:
        - setup
