description: >
  In the simplest case, config.yml looks like this.
  main.yml is a configuration file that will be passed to the continue API.

  NOTE: Enable dynamic config on project settings page.

usage:
  version: 2.1
  orbs:
    bundler: dr666m1/yaml-bundler@0.0.1
  workflows:
    setup:
      jobs:
        - bundler/continue:
            filepath: main.yml
